name: version bump and create PR for changes

on:
  push:
    branches:
      - main

env:
  NODE_ENV: 'development'

jobs:
  update_changelog:
    runs-on: ubuntu-20.04
    if: |
      github.repository_owner == 'jacderida' &&
      !startsWith(github.event.head_commit.message, 'chore(release):')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: bump version
        uses: jacderida/rust-version-bump-branch-creator@workspace_versioning
        with:
          token: ${{ secrets.MERGE_BUMP_BRANCH_TOKEN }}
